sudo: required
services:
    - docker

before_install:
    - gem install bundler --pre
    - docker build -t inguilty/docker-react -f Dockerfile.dev .

script:
    - travis_wait 30 docker run inguilty/docker-react npm run test -- --coverage