sudo: required
services:
    - docker

before_install:
    - gem install bundler --pre
    - docker build -t inguilty/docker-react -f Dockerfile.dev .

script:
    - docker run inguilty/docker-react set CI=true&&npm run test "--coverage"