sudo: required
services:
    - docker

before_install:
    - gem install bundler --pre
    - docker build -t inguilty/docker-react -f Dockerfile.dev .

script:
    - docker run inguilty/docker-react npm run test "--coverage" 
    #-- --coverage