sudo: required
services:
    - docker

before_install:
    - gem install bundler --pre
    - docker build -t inguilty/docker-react -f Dockerfile.dev .

install: travis_wait 30 mvn install

script:
    - docker run inguilty/docker-react npm run test -- --coverage